export const UPDATE_ORDER_BOOK_BIDS = 'UPDATE_ORDER_BOOK_BIDS';
export const UPDATE_ORDER_BOOK_ASKS = 'UPDATE_ORDER_BOOK_ASKS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET';
export const SET_PRECISION = 'SET_PRECISION';
